

GET http://localhost:5029
###


GET http://localhost:5029/api/departments?searchValue=SALL

###

POST http://localhost:5029/api/departments
content-type:application/json

{
    "departmentName":"HR",
    "managerId": 103
}
###


PUT http://localhost:5029/api/departments

###

DELETE http://localhost:5029/api/departments/6d096f5a-addc-4a5e-9362-86501ac1e811
###